### ISSUE TITLE
Unable to use static type checks without method wrappers

### ISSUE THREAD

**Issue by coderanger** [plum-umd/rdl#20]
From the code in `type`, it only sets the method source location in `$__rdl_info` if either wrapping is enabled, or if `typecheck` is `:now`. This means you can't run a manual typecheck without turning on method wrapping (or injecting the source locations myself). Similarly, `typecheck: :later` only works if wrapping is enabled.

**Comment by coderanger** [comment]
For the sake of repro case:

```ruby
require 'rdl'

class Foo
  def foo
    "one"
  end

  type :foo, '() -> Fixnum', wrap: false
end

RDL::Typecheck.typecheck(Foo, :foo)
```

```
lib/rdl/typecheck.rb:167:in `get_ast': No file for Foo#foo (RuntimeError)
	from lib/rdl/typecheck.rb:197:in `typecheck'
	from mini.rb:14:in `<main>'
```

**Comment by coderanger** [comment]
Using either the deferred declaration syntax or method wrappers ensures the source location is set.

**Comment by jeffrey-s-foster** [comment]
Thanks for the bug report.

I think that probably if `typecheck` isn't passed to `type` then the source location shouldn't be recorded, so that there's no extra overhead except recording the annotation in that case. (It's a pretty minor difference, of course.) Unless there's an important use case for this?

But definitely if `typecheck: :sym` is passed then the source location should be stored. I just pushed a fix to the `dev` branch that I think solves this part of it.
