### ISSUE TITLE
Methods that change the type of self

### ISSUE THREAD

**Issue by jeffrey-s-foster** [plum-umd/rdl#3]
There are a few methods that actually change the type of self: map! (Array, Set) is one example. How do we write down its type?

**Comment by YursTruly** [comment]
I'm not sure if we can check if a method is a mutator, but the plan is to keep a log of the previous value within the typesig execution so that a post check can determine correct behavior.

-Alex

On Monday, July 21, 2014 4:47 PM, Jeff Foster notifications@github.com wrote:

There are a few methods that actually change the type of self: map! (Array, Set) is one example. How do we write down its type?

**Comment by j2ren** [comment]
In RTC, we did something like
typesig("foo: (Fixnum) -> Array<Fixnum>", {:mutate => true})

Do we want to do the same in RDL?

**Comment by jeffrey-s-foster** [comment]
We definitely need special handling for methods that change the type of self (at least, we need a contract check that we can't currently express with a typesig). But for average mutators, I wouldn't put in an annotation.
